 export const images = 
 [ {
    id:1,
    image:"./images/project_1.png",
    link:"https://calculator-app-nine.vercel.app/",
 },
 {
    id:2,
    image:"./images/project_2.png",
    link:"https://single-price-grid-component-master-orpin-two.vercel.app/",
 },
 {
    id:3,
    image:"./images/project_3.png",
    link:"https://social-proof-section-master-one-hazel.vercel.app/",
 },
 {
    id:4,
    image:"./images/project_4.png",
    link:"https://stats-preview-card-component-main-nine.vercel.app/",
 },
 {
    id:5,
    image:"./images/project_5.png",
    link:"https://testimonials-grid-section-main-murex.vercel.app/",
 },
 {
    id:6,
    image:"./images/project_6.png",
    link:"https://3-column-preview-card-component-main-lovat.vercel.app/",
 },
 {
    id:7,
    image:"./images/project_7.png",
    link:"https://practical-benz-2deeb5.netlify.app/",
 },
 {
    id:8,
    image:"./images/project_8.jfif",
    link:"https://frontend-adip-deployment.vercel.app/",
 },
 {
   id:9,
   image:"./images/project_9.png",
   link:"https://behance-clone-virid.vercel.app/",
},
{
   id:10,
   image:"./images/project_10.png",
   link:"https://rentify-frontend-coral.vercel.app/",
},
{
   id:11,
   image:"./images/project_11.png",
   link:"https://github.com/Deepthi-Ramesh/StudentDB",
}

 
]